-- Getting a specific group
SELECT A.NAME, A.PHONE 
FROM CONTACTS A
JOIN GROUPCOLLECTION B ON A.EMAIL = B.CONTACT_ID
JOIN GROUPSCATEGORY C ON B.GROUP_ID = C.ID
WHERE C.NAME = 'Young Adults';


-- Getting user PREFRENCES
SELECT U.NAME , P.PREF1, P.PREF2, P.PREF3
FROM CONTACTS U, PREFRENCES P
WHERE U.EMAIL = 'jsmith1985@gmail.com' AND P.CONTACT_ID = 'jsmith1985@gmail.com';